/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.openqa.selenium.WebDriver;

public class App {

    public static void main(String[] args) {
        
        Checkbox checkbox = new Checkbox();
        try{
            checkbox.initDriver();
            checkbox.launchBrowser();
            checkbox.testCase();
        } catch(Exception e){
            System.err.println("Test Failed:   "+ e.getMessage());
            e.printStackTrace();
        } finally{
            checkbox.closeBrowser();
        } 
    }
}
