/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.openqa.selenium.WebDriver;

public class App {

    public static void main(String[] args) {
        /*
        Checkbox checkbox = new Checkbox();
        try{
            checkbox.initDriver();
            checkbox.launchBrowser();
            checkbox.testCase();
            checkbox.testCase02();
            checkbox.testCase03();
        } catch(Exception e){
            System.err.println("Test Failed:   "+ e.getMessage());
            e.printStackTrace();
        } finally{
            checkbox.closeBrowser();
        } 
        */
        Radiobutton radiobtn = new Radiobutton();

        try{
            radiobtn.initDriver();
            radiobtn.openURL();
            radiobtn.testCase01();
            radiobtn.testCase02();
            radiobtn.testCase03();
        }catch(Exception e){
            System.out.println("Exception occurred : "+e.getMessage());
        }finally{
            radiobtn.closeBrowser();
        }
    }
}
